### ISSUE TITLE
Provide simple OOP Interface

### ISSUE THREAD

**Issue by mithun** [uperl/Archive-Libarchive-XS#32]
Thanks for your work on a complete binding to libarchive.

However, the current interface is too verbose and more 'C'-like. Having an OOP interface, preferable one that matches Archive::Extract, will help users like me a lot. Plus it will be relatively easy (minimal code changes) to convert existing code from Archive::Extract[::Libarchive] to this distribution.

-Mithun

**Comment by plicease** [comment]
`Archive::Libarchive` does this.
