### ISSUE TITLE
The `open1`  interface doesn't work ( SIGSEGV )

### ISSUE THREAD

**Issue by ribasushi** [uperl/Archive-Libarchive-XS#38]
A sequence like this should work according to the documentation, yet it segfaults:
```
  my $cb1_reader = Archive::Libarchive::XS::archive_read_new;
  Archive::Libarchive::XS::archive_read_support_format_tar( $cb1_reader );
  Archive::Libarchive::XS::archive_read_set_read_callback( $cb1_reader, sub {
    Archive::Libarchive::XS::ARCHIVE_OK,
    $tar_data,
  });

  Archive::Libarchive::XS::archive_read_open1( $cb1_reader );
```

Attached find a complete reproduction: [arch_wtf.txt](https://github.com/plicease/Archive-Libarchive-XS/files/1107777/arch_wtf.txt)

**Comment by plicease** [comment]
I've actually run into this when implementing `Archive::Libarchive`.  If you don't set a data to something then it will seg fault.  If you use `archive_read_set_callback_data` to set the data to `undef` / NULL it should work.
